-- =============================================
-- Project: Corporate Banking Data Migration
-- Author: Lignesh A.R. - Snowflake Developer
-- =============================================

USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS CORPORATE_BANKING_DB;
CREATE SCHEMA IF NOT EXISTS CORPORATE_BANKING_DB.CORE;

USE DATABASE CORPORATE_BANKING_DB;
USE SCHEMA CORE;

-- Customers Table
CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    ACCOUNT_NUMBER VARCHAR(50) UNIQUE,
    ACCOUNT_TYPE VARCHAR(30),
    BALANCE NUMBER(15,2),
    OPEN_DATE DATE,
    STATUS VARCHAR(20),
    KYC_STATUS VARCHAR(20)
);

-- Transactions Table
CREATE OR REPLACE TABLE TRANSACTIONS (
    TXN_ID NUMBER AUTOINCREMENT,
    TXN_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CUSTOMER_ID NUMBER,
    ACCOUNT_NUMBER VARCHAR(50),
    TXN_TYPE VARCHAR(20),
    AMOUNT NUMBER(15,2),
    CURRENCY VARCHAR(3) DEFAULT 'USD',
    DESCRIPTION VARCHAR(200),
    STATUS VARCHAR(20) DEFAULT 'COMPLETED',
    SOURCE_SYSTEM VARCHAR(50) DEFAULT 'ORACLE_LEGACY'
);

-- Clone for Time Travel demo
CREATE OR REPLACE TABLE TRANSACTIONS_HISTORY CLONE TRANSACTIONS;