-- =============================================
-- 03_live_transaction_proc.sql
-- Stored Procedure for Live Bank Transactions
-- =============================================

CREATE OR REPLACE PROCEDURE PROCESS_LIVE_TRANSACTION(
    P_CUSTOMER_ID NUMBER,
    P_ACCOUNT_NUMBER VARCHAR,
    P_TXN_TYPE VARCHAR,
    P_AMOUNT NUMBER,
    P_DESCRIPTION VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO TRANSACTIONS (CUSTOMER_ID, ACCOUNT_NUMBER, TXN_TYPE, AMOUNT, DESCRIPTION, STATUS)
    VALUES (P_CUSTOMER_ID, P_ACCOUNT_NUMBER, P_TXN_TYPE, P_AMOUNT, P_DESCRIPTION, 'COMPLETED');
    
    UPDATE CUSTOMERS 
    SET BALANCE = BALANCE + CASE WHEN P_TXN_TYPE = 'CREDIT' THEN P_AMOUNT ELSE -P_AMOUNT END
    WHERE ACCOUNT_NUMBER = P_ACCOUNT_NUMBER;
    
    RETURN 'Transaction Processed Successfully!';
END;
$$;

-- Example Call:
-- CALL PROCESS_LIVE_TRANSACTION(1001, 'ACC1001', 'DEBIT', 25000, 'Vendor Payment May 2026');